name: Blacken
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        line-length: '120'
        path: 'finder/'
        sanity-check: 'safe'
        only-check: 'no'
